server:
  port: ${API_PORT}

spring:
  application:
    name: KNUTICE-API

  data:
    mongodb:
      database: ${MONGO_DATABASE}
      uri: ${MONGO_URI}

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  access-token:
    plus-hour: ${JWT_ACCESS_PLUS_HOUR}
  refresh-token:
    plus-hour: ${JWT_REFRESH_PLUS_HOUR}

crawler:
  server:
    address: ${CRAWLER_SERVER_ADDRESS}

file:
  upload-dir: ${FILE_UPLOAD_DIR}
  context-path: ${FILE_CONTEXT_PATH}

url:
  scheme: ${URL_SCHEME}
  host: ${URL_HOST}
  allowed-origins:
    - http://localhost:5173
    - ${URL_ORIGIN}

reading-room:
  root-url: ${READING_ROOM_ROOT_URL}
  endpoints:
    seats: ${READING_ROOM_SEATS_ENDPOINT}
    status: ${READING_ROOM_STATUS_ENDPOINT}

logging:
  level:
    org:
      springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  metrics:
    tags:
      application: ${spring.application.name}